  name: Auto-approve Dependabot PRs

on:
  pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]') && contains(github.event.pull_request.body, 'will automatically merge')
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
