on:
  pull_request:
    branches:
    - master

jobs:
  auto-approve:
    name: Auto-approve Dependabot PRs
    runs-on: ubuntu-latest
    steps:
    - name: Auto Approve Dependabot
      uses: cognitedata/auto-approve-dependabot-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
